In [1]:
import numpy as np

np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/corsair/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/corsair/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/corsair/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\

In [2]:
np.__version__

'1.18.1'

На вход подаётся список чисел (строка, где числа разделены запятой).

Создайте и сохраните:

- в переменную V1 Numpy вектор из этих чисел в том же порядке
- в переменную V2 Numpy вектор, содержащий только предпоследнее число (это должен быть именно вектор!)
- в переменную V3 Numpy вектор из этих чисел в обратном порядке
- в переменную V4 Numpy вектор из этих чисел, начиная с 0-ого, через 2 (т.е. каждое третье число)
- в переменную V5 Numpy вектор, созданный из генератора Range, содержащий столько элементов, сколько было передано чисел на вход

Примечание. В этой задаче не нужно ничего выводить на печать. Только создать вектора.

In [3]:
in_ = [1, 2, 3, 4, 5.0, 6, 7, 8, 9, 10]
# in_ = input().split(', ')
in_ = list(map(float, in_))

V1 = np.array(in_)
V2 = np.array(in_[-2])
V3 = np.array(in_[::-1])
V4 = np.array(in_[::3])
V5 = np.array(range(len(in_)))

print(V5)

[0 1 2 3 4 5 6 7 8 9]


[](https://ucarecdn.com/0f65b331-4667-4c48-99e7-b192bc3f65e6/)

На вход подаётся 2 списка целых чисел (они представляют из себя вектора равной длины, т.е. с одинаковым количеством элементов).

Используя векторные операции создайте и сохраните:

- в переменную V1 Numpy вектор с числами из 1 строки
- в переменную V2 Numpy вектор с числами из 2 строки
- в переменную V3 Numpy вектор с покоординатными суммами V1 и V2
- в переменную V4 Numpy вектор с покоординатными произведениями каждого второго числа V1 на каждое второе число V2, развёрнутого в обратном порядке


In [4]:
l1 = '1, 2, 3, 4'
l2 = '10, 20, 30, 40'

V1 = np.array(list(map(int, l1.split(', '))))
V2 = np.array(list(map(int, l2.split(', '))))
V3 = V1 + V2
V4 = V1[::2] * V2[::-2]
V4

array([40, 60])

На вход подаётся 2 набора целых чисел.

Создайте вектор V такой, что он будет содержать числа из 1 набора, делящиеся нацело на предпоследнее число из 2 набора и разделённые на это число.

Если таких чисел не найдётся, то вектор V будет пустым (т.е. не будет содержать элементов).

 

Примечание. В этой задаче не нужно ничего выводить на печать. Только создать вектора.

In [5]:
l1 = '1, 2, 3, 4, 5, 6'
l2 = '1, 2, 3, 4'

V1 = np.array(list(map(int, l1.split(', '))))
V2 = np.array(list(map(int, l2.split(', '))))

V3_1 = np.array(V1 % V2[-2] == 0)
print(V3_1)

V3 =  V1[V1 % V2[-2] == 0] / V2[-2]
V3

[False False  True False False  True]


array([1., 2.])

В этой задаче нам даны 3 переменные: A1, A2, A3. Каждая содержит вектор с 2 координатами соответствующей вершины треугольника.

Найдите площадь треугольника и выведите её на печать.
Если все 3 точки лежат на одной прямой, то площадь треугольника равна 0.

Ответ проверяется с точностью до 4 знака после запятой.

In [6]:
from math import sqrt

A1 = np.array((-1, 1))
A2 = np.array((2, 5))
A3 = np.array((5, -3))

A1 = np.array((-1, 2))
A2 = np.array((2, 3))
A3 = np.array((5, 4))

l1 = sqrt((A1[0] - A2[0])**2 + (A1[1] - A2[1])**2)
l2 = sqrt((A1[0] - A3[0])**2 + (A1[1] - A3[1])**2)
l3 = sqrt((A2[0] - A3[0])**2 + (A2[1] - A3[1])**2)

#print(l1, l2, l3)
p = (l1 + l2 + l3)/2

S = sqrt(p*(p-l1)*(p-l2)*(p-l3))
print(S)

0.0


Переменная M1 содержит Numpy матрицу.

Произведите операции последовательно:

1. Замените значения в предпоследней строке на значения по формуле:

sin(x⋅π6)\LARGE sin(\frac{x \cdot \pi}{6})sin(6x⋅π), где x - старое значение

2. Замените значения в предпоследнем столбце на значения по форуме:

ex\LARGE e^xex

 

Примечание. Для ячейки на пересечении предпоследнего столбца и предпоследней строки значение ячейки будет изменено по формуле: 

esin(x⋅π6)\LARGE e^{sin(\frac{x \cdot \pi}{6})}esin(6x⋅π​)

In [7]:
M = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
M[1, 1]

5

In [9]:
M[0]

array([1, 2, 3])

In [10]:
M[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
M[:2][:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
M[:2][:1]

array([[1, 2, 3]])

In [13]:
M[:, 0]

array([1, 4, 7])

### Скалярное произведение

In [14]:
V1 = np.array((1, 2, 3, 4))
V2 = np.array((5, 6, 7, 8))

V3 = V1 * V2
print(V3, np.sum(V3))
print(V1.dot(V2))

[ 5 12 21 32] 70
70


In [15]:
M1 = np.array((
    (1., 2., 3., 0.),
    (4., 5., 6., 0.),
    (0., 1., 1., 6.),
    (7., 8., 9., 0.)
))

M1[-2] = np.sin(M1[-2]*np.pi/6)
M1[:, -2] = np.exp(M1[:, -2])
print(M1)

[[1.00000000e+00 2.00000000e+00 2.00855369e+01 0.00000000e+00]
 [4.00000000e+00 5.00000000e+00 4.03428793e+02 0.00000000e+00]
 [0.00000000e+00 5.00000000e-01 1.64872127e+00 1.22464680e-16]
 [7.00000000e+00 8.00000000e+00 8.10308393e+03 0.00000000e+00]]


- Решило: 473
- Успешных решений: 40% 

In [17]:
np.save('M1_array', M1)
np.savetxt('M1_array.txt', M1)

### 3.2

Считайте строку, где значения заданы через пробел shape и dtype

Последнее значение в строке может быть либо числом (тогда это последнее значение кортежа shape, либо строкой dtype)

    shape - атрибут, задающий размеры матрицы нолей (позволяет вернуть вектор-строку, вектор-столбец, матрицу, куб и т.д.)
    dtype - тип данных, использующихся для значений матрицы. По-умолчанию используется numpy.float64.

Создайте матрицу Z размера shape, со значениями типа dtype (если dtype не указан, используйте numpy.float64)

In [30]:
s = '2 3 bool'
#s = input()
attrs = s.split()

Z = None
type_ = arrts[-1]

# if isdigit() type_ 

if len(attrs) == 1:
    Z = np.zeros(int(attrs[0]), dtype=np.float64)
elif len(attrs) == 2:
    Z = np.zeros((int(attrs[0]), int(attrs[1])), dtype=np.float64)
else:
    Z = np.zeros((int(attrs[0]), int(attrs[1])), dtype=attrs[2])
    
Z

array([[False, False, False],
       [False, False, False]])