In [60]:
import numpy as np

np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/corsair/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/corsair/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/corsair/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\

In [2]:
np.__version__

'1.18.1'

На вход подаётся список чисел (строка, где числа разделены запятой).

Создайте и сохраните:

- в переменную V1 Numpy вектор из этих чисел в том же порядке
- в переменную V2 Numpy вектор, содержащий только предпоследнее число (это должен быть именно вектор!)
- в переменную V3 Numpy вектор из этих чисел в обратном порядке
- в переменную V4 Numpy вектор из этих чисел, начиная с 0-ого, через 2 (т.е. каждое третье число)
- в переменную V5 Numpy вектор, созданный из генератора Range, содержащий столько элементов, сколько было передано чисел на вход

Примечание. В этой задаче не нужно ничего выводить на печать. Только создать вектора.

In [3]:
in_ = [1, 2, 3, 4, 5.0, 6, 7, 8, 9, 10]
# in_ = input().split(', ')
in_ = list(map(float, in_))

V1 = np.array(in_)
V2 = np.array(in_[-2])
V3 = np.array(in_[::-1])
V4 = np.array(in_[::3])
V5 = np.array(range(len(in_)))

print(V5)

[0 1 2 3 4 5 6 7 8 9]


[](https://ucarecdn.com/0f65b331-4667-4c48-99e7-b192bc3f65e6/)

На вход подаётся 2 списка целых чисел (они представляют из себя вектора равной длины, т.е. с одинаковым количеством элементов).

Используя векторные операции создайте и сохраните:

- в переменную V1 Numpy вектор с числами из 1 строки
- в переменную V2 Numpy вектор с числами из 2 строки
- в переменную V3 Numpy вектор с покоординатными суммами V1 и V2
- в переменную V4 Numpy вектор с покоординатными произведениями каждого второго числа V1 на каждое второе число V2, развёрнутого в обратном порядке


In [4]:
l1 = '1, 2, 3, 4'
l2 = '10, 20, 30, 40'

V1 = np.array(list(map(int, l1.split(', '))))
V2 = np.array(list(map(int, l2.split(', '))))
V3 = V1 + V2
V4 = V1[::2] * V2[::-2]
V4

array([40, 60])

На вход подаётся 2 набора целых чисел.

Создайте вектор V такой, что он будет содержать числа из 1 набора, делящиеся нацело на предпоследнее число из 2 набора и разделённые на это число.

Если таких чисел не найдётся, то вектор V будет пустым (т.е. не будет содержать элементов).

 

Примечание. В этой задаче не нужно ничего выводить на печать. Только создать вектора.

In [5]:
l1 = '1, 2, 3, 4, 5, 6'
l2 = '1, 2, 3, 4'

V1 = np.array(list(map(int, l1.split(', '))))
V2 = np.array(list(map(int, l2.split(', '))))

V3_1 = np.array(V1 % V2[-2] == 0)
print(V3_1)

V3 =  V1[V1 % V2[-2] == 0] / V2[-2]
V3

[False False  True False False  True]


array([1., 2.])

В этой задаче нам даны 3 переменные: A1, A2, A3. Каждая содержит вектор с 2 координатами соответствующей вершины треугольника.

Найдите площадь треугольника и выведите её на печать.
Если все 3 точки лежат на одной прямой, то площадь треугольника равна 0.

Ответ проверяется с точностью до 4 знака после запятой.

In [6]:
from math import sqrt

A1 = np.array((-1, 1))
A2 = np.array((2, 5))
A3 = np.array((5, -3))

A1 = np.array((-1, 2))
A2 = np.array((2, 3))
A3 = np.array((5, 4))

l1 = sqrt((A1[0] - A2[0])**2 + (A1[1] - A2[1])**2)
l2 = sqrt((A1[0] - A3[0])**2 + (A1[1] - A3[1])**2)
l3 = sqrt((A2[0] - A3[0])**2 + (A2[1] - A3[1])**2)

#print(l1, l2, l3)
p = (l1 + l2 + l3)/2

S = sqrt(p*(p-l1)*(p-l2)*(p-l3))
print(S)

0.0


Переменная M1 содержит Numpy матрицу.

Произведите операции последовательно:

1. Замените значения в предпоследней строке на значения по формуле:

sin(x⋅π6)\LARGE sin(\frac{x \cdot \pi}{6})sin(6x⋅π), где x - старое значение

2. Замените значения в предпоследнем столбце на значения по форуме:

ex\LARGE e^xex

 

Примечание. Для ячейки на пересечении предпоследнего столбца и предпоследней строки значение ячейки будет изменено по формуле: 

esin(x⋅π6)\LARGE e^{sin(\frac{x \cdot \pi}{6})}esin(6x⋅π​)

In [7]:
M = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
M[1, 1]

5

In [9]:
M[0]

array([1, 2, 3])

In [10]:
M[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
M[:2][:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
M[:2][:1]

array([[1, 2, 3]])

In [13]:
M[:, 0]

array([1, 4, 7])

### Скалярное произведение

In [14]:
V1 = np.array((1, 2, 3, 4))
V2 = np.array((5, 6, 7, 8))

V3 = V1 * V2
print(V3, np.sum(V3))
print(V1.dot(V2))

[ 5 12 21 32] 70
70


In [15]:
M1 = np.array((
    (1., 2., 3., 0.),
    (4., 5., 6., 0.),
    (0., 1., 1., 6.),
    (7., 8., 9., 0.)
))

M1[-2] = np.sin(M1[-2]*np.pi/6)
M1[:, -2] = np.exp(M1[:, -2])
print(M1)

[[1.00000000e+00 2.00000000e+00 2.00855369e+01 0.00000000e+00]
 [4.00000000e+00 5.00000000e+00 4.03428793e+02 0.00000000e+00]
 [0.00000000e+00 5.00000000e-01 1.64872127e+00 1.22464680e-16]
 [7.00000000e+00 8.00000000e+00 8.10308393e+03 0.00000000e+00]]


- Решило: 473
- Успешных решений: 40% 

In [16]:
np.save('M1_array', M1)
np.savetxt('M1_array.txt', M1)

### 3.2

Считайте строку, где значения заданы через пробел shape и dtype

Последнее значение в строке может быть либо числом (тогда это последнее значение кортежа shape, либо строкой dtype)

    shape - атрибут, задающий размеры матрицы нолей (позволяет вернуть вектор-строку, вектор-столбец, матрицу, куб и т.д.)
    dtype - тип данных, использующихся для значений матрицы. По-умолчанию используется numpy.float64.

Создайте матрицу Z размера shape, со значениями типа dtype (если dtype не указан, используйте numpy.float64)

In [17]:
import numpy as np
nptypes = {'int64', 'float32', 'complex', 'bool', 
           'object', 'string_', 'unicode_'
          }

s = '2 3 bool'
#s = input()
attrs = s.split()

Z = None
type_ = attrs[-1]

if type_.isdigit():
    attrs = list(map(int, attrs))
    # print(tuple(attrs))
    Z = np.zeros(tuple(attrs))
else:
    attrs = list(map(int, attrs[:-1]))
    print(tuple(attrs))
    Z = np.zeros(tuple(attrs), dtype=type_)
    
Z

(2, 3)


array([[False, False, False],
       [False, False, False]])

### 4

Посчитайте размер матрицы Z в байтах и выведите его на печать.

Чтобы узнать размер (в байтах) 1 элемента матрицы используйте атрибут https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.ndarray.itemsize.html

In [18]:
Z = np.zeros((10,10))
print(Z.size*Z.itemsize)

800


### 5

Выведите на печать встроенную документацию для функции add numpy, а потом объекта numpy.array.


In [19]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [20]:
np.info(np.array)

array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    __array__ method returns an array, or any (nested) sequence.
dtype : data-type, optional
    The desired data-type for the array.  If not given, then the type will
    be determined as the minimum type required to hold the objects in the
    sequence.
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if __array__ returns a copy, if obj is a nested sequence,
    or if a copy is needed to satisfy any of the other requirements
    (`dtype`, `order`, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly created array will be in C order (row major) unless 'F' is
    specified, in which case it will be in Fortran order (column major).
    If object is 

### 6

Считайте 2 числа:

    n - размер Numpy вектора
    x - координата элемента вектора, который должен быть равен 1. Остальные элементы вектора должны быть равны 0.

Сохраните вектор в переменную Z.

Примечание. В этой задаче не нужно ничего выводить на печать. Только создать вектор Z. 

In [21]:
#n = int(input())
#x = int(input())
n, x = 10, 5

Z = np.zeros(n)
Z[x] = 1

Z

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

### 7

Считайте 2 числа n, m.

Создайте вектор Z состоящий из чисел от n до m.

Примечание. В этой задаче не нужно ничего выводить на печать. Только создать вектор Z. 

In [22]:
#n = int(input())
#m = int(input())
n, m = 4, 10

Z = np.array(range(n, m+1))
Z

array([ 4,  5,  6,  7,  8,  9, 10])

### 8

Дан вектор Z. "Разверните" его.

In [23]:
Z = np.array([1, 2, 3, 4])
Z = Z[::-1]

Z

array([4, 3, 2, 1])

### 9
Считайте 3 числа:

    n - количество элементов матрицы
    m и l - размеры матрицы (число строк и столбцов соответственно)

Заполните матрицу Z числами от 0 до n-1 по порядку (сперва строки, потом столбцы).
Гарантируется, что m*l = n, т.е. все элементы "влезут" в матрицу и не останется пустых мест.

In [24]:
# n = int(input())
# m, l = input().split()

n = 6
m, l = 2, 3

# Z = np.array(list(range(n)), (int(m), int(l)), dtype=np.float64)
Z = np.array(list(range(n)))
Z = Z.reshape(int(m), int(l))

Z

array([[0, 1, 2],
       [3, 4, 5]])

### 10.1

Дан вектор Z

Запишите в переменную NonZerros индексы ненулевых элементов.

Используйте функцию https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.nonzero.html

In [25]:
import numpy as np

Z = np.array([1, 0, 2, 0, 3, 0, 4])
print(Z.nonzero())

(array([0, 2, 4, 6], dtype=int64),)


### 10.2

Дана матрица чисел Z (Z может быть 1, 2 или даже 3 мерной).

Выведите на печать список чисел из этой матрицы, которые больше 3.

In [26]:
Z = np.array([[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9],
          [0, 0, 9]])

A = Z[Z>3]

list(A)

[4, 5, 6, 7, 8, 9, 9]

### 11

Считайте число n

Создайте единичную матрицу размера n, сохраните результат в переменную Z.

In [27]:
n = 9

Z = np.eye(n)

Z

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### 12

Считайте 3 числа: n, m, l.

Зафиксируйте значение генератора случайных чисел Numpy с помощью
`numpy.random.seed(42)`
Создайте матрицу n*m*l из случайных чисел (от 0 до 1) и сохраните результат в переменную Z.

In [28]:
np.random.seed(42)

l, m, n = 2, 2, 2

Z = np.random.rand(l*m*n)
Z = Z.reshape(n, m, l)

Z

array([[[0.37454012, 0.95071431],
        [0.73199394, 0.59865848]],

       [[0.15601864, 0.15599452],
        [0.05808361, 0.86617615]]])

### 12 v2
Другой способ решения

In [29]:
np.random.seed(42)
Z = np.random.rand(l, m, n)
Z

array([[[0.37454012, 0.95071431],
        [0.73199394, 0.59865848]],

       [[0.15601864, 0.15599452],
        [0.05808361, 0.86617615]]])

```python
np.random.seed(42)
n, m, l = map(int, input().split())
Z = np.random.random((n, m, l))
```

### 13

Считайте 2 числа: n, m.

Зафиксируйте значение генератора случайных чисел Numpy с помощью

numpy.random.seed(42)

Создайте матрицу n*m из случайных чисел (от 0 до 1).
Выведите на печать значение минимального и максимального чисел в получившейся матрице (каждое с новой строки).

In [30]:
np.random.seed(42)

#n, m = map(int, input().split())
n, m = 5, 8

Z = np.random.rand(n, m)
print(np.min(Z))
print(np.max(Z))

0.020584494295802447
0.9699098521619943


### 14

Считайте 2 числа: n, m.

Зафиксируйте значение генератора случайных чисел Numpy с помощью

numpy.random.seed(42)

Создайте матрицу n*m из случайных чисел (от 0 до 1).
Выведите на печать значение среднего для всей матрицы.


In [31]:
np.random.seed(42)

# n, m = map(int, input().split())
n, m = 4, 6

Z = np.random.rand(n, m)
print(np.sum(Z)/Z.size)
print(np.mean(Z))

0.44016245896496015
0.44016245896496015


### 14.1

Считайте 2 числа: n, m.

Зафиксируйте значение генератора случайных чисел Numpy с помощью

`numpy.random.seed(42)`

Создайте матрицу n*m из случайных чисел (от 0 до 1).
Найдите среднее значение для каждого из столбцов.
Выведите на печать значение минимального и максимального среднего по столбцам (каждое с новой строки).

**ПРИМЕР**
![](https://ucarecdn.com/3365e7de-3640-463c-8e48-3bc4a0668413/)
   
- 0.15, 0.55 и 0.88 - средние значения по столбцам.
- 0.15 - минимальное среднее
- 0.88 - максимальное среднее


Используйте атрибут axis функции https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.mean.html


In [32]:
import numpy as np

np.random.seed(42)
#n, m = map(int, input().split())
n, m = 10, 10

Z = np.random.rand(n, m)
# print(Z.mean())
# print(np.mean(Z))

M = Z.mean(axis=0)
print(M.min())
print(M.max())


0.3431350563981565
0.5727443030932713


### 15

Считайте 2 числа: n, m.
Создайте матрицу размера n*m такую что:

    На границе матрицы будут стоять 1
    Внутри матрицы будут стоять 0

Сохраните матрицу в переменную Z.

**ПРИМЕР**

![](https://ucarecdn.com/25193712-fa68-44e8-9ad3-40747c17474c/)

Примечание. В этой задаче не нужно ничего выводить на печать. Только создать матрицу Z. 

In [33]:
import numpy as np

#n, m = map(int, input().split())
n, m = 3, 4

Z = np.zeros((n, m))
Z[0] = 1
Z[-1] = 1
Z[:, 0] = 1
Z[:, -1] = 1

Z

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [34]:
Z = np.array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Z = np.pad(Z, 1, 'constant')

Z

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 0],
       [0, 4, 5, 6, 0],
       [0, 7, 8, 9, 0],
       [0, 0, 0, 0, 0]])

### 17
Что вернёт каждое из выражений?


In [35]:
import numpy

np.nan in set([np.nan])
numpy.isnan(numpy.nan)
numpy.nan - numpy.nan
0.3 == 3 * 0.1
0 * numpy.nan
numpy.nan == numpy.nan
numpy.inf > numpy.nan

False

Любопытная штука, эти np.nan. Их определение умудряется обходить даже равенство идентификаторов. Попробуйте запустить такой код, возможно, вас тоже развлечёт, как меня:

In [36]:
n = np.nan
m = np.nan
print(id(n), id(m), sep='\n')
print(id(n) == id(m))
print(n == m)

2831070084208
2831070084208
True
False


### 18.1

Считайте число n.
Создайте диагональную матрицу размера `n*n`. На главной диагонали должны быть числа от 1 до n.
Сохраните матрицу в переменную Z.

In [37]:
n = 3
Z = np.diag(np.arange(1, n+1))

Z

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

### 18.2

Считайте 2 числа:

    x - сдвиг для единственной ненулевой диагонали в матрице.
    k - верхняя граница для интервала чисел на диагонали (т.е. если k = 5, то на диагонали будут стоять числа 1, 2, 3, 4 и 5)

Договоримся о значениях x:

    x = 0 - это главная диагональ матрицы
    x<0 - диагональ сдвигается вниз на |x| ячеек (если x = -1, то первая не нулевая ячейка будет с координатами (1,0))
    x>0 - диагональ сдвигается вправо на |x| ячеек (если x = 1, то первая ненулевая ячейка будет с координатами (0,1))

Обратите внимание, что размер матрицы изменяется в зависимости от сдвига, т.к. вам надо уместить все числа от 1 до k!

Сохраните такую матрицу в переменную Z.

In [38]:
import numpy as np

# x, k = map(int, input().split())
x, k = 1, 2

Z = np.diag(np.arange(1,k+1),x)
Z

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

### 19 (21)

Считайте 2 числа: n, m.
Создайте матрицу размера n*m и "раскрасьте" её в шахматную раскраску.

    0 - "чёрное"
    1 - "белое"

Ячейка с координатами (0, 0) всегда "чёрная" (т.е. элемент (0, 0) равен 0).
Матрицу сохраните в переменную Z.

In [39]:
n, m = 5, 5

Z = np.zeros((n, m))


Z[::2, 1::2] = 1
Z[1::2, ::2] = 1
Z

array([[0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.]])

### 22 Нормализация

Используйте формулу 

    xnew=x−μσ x_{new} = \frac {x - \mu}{\sigma} xnew​=σx−μ​ ,

где

    x x x - старое значение
    xnew x_{new} xnew​ - новое значение
    μ \mu μ - среднее значение (по всей матрице)
    σ \sigma σ - стандартное отклонение (по всей матрице)

для того чтобы "нормализовать" матрицу.

Мы пока не будем углубляться в математическую суть этой операции, важно лишь, что оба значения для матрицы могут быть вычислены стандартными функциями numpy и вам не нужно звать на помощь статистику)


In [61]:
import numpy as np 

Y = np.array([[1, 2], [2, 1]])
Y = np.array([[99, 11, 55], [33, 66, 99]])

m = np.mean(Y)
st = np.std(Y)

Z = (Y - np.mean(Y))/np.std(Y)
print(Z)

Z = np.around(Z, 2)

Z

[[ 1.19464826 -1.53597633 -0.17066404]
 [-0.85332019  0.17066404  1.19464826]]


array([[ 1.19, -1.54, -0.17],
       [-0.85,  0.17,  1.19]])

- Решило: 505
- Успешных решений: 50% 

### 24.1 Скалярное произведение векторов

Переменные A и B содержат по numpy вектору. Найдите их скалярное произведение и сохраните в переменную Z.

A и B могут содержать как int, так и float.

Примечание. В этой задаче не нужно ничего выводить на печать. Только создать Z. 

In [63]:
A = np.array([1.5, 2.5, 3.5])
B = np.array([4, 5, 6])

Z = A.dot(B)

Z

39.5

- Решило: 524
- Успешных решений: 87% 

In [84]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [11.5],
    [12.5],
    [13.5]
])

print(A)
print(B)

if A.shape[1] == B.shape[0]:
    Z = A.dot(B)
else:
    Z = "Упс! Что-то пошло не так..."

#np.multiply(A, B)
print(A.shape,  B.shape, Z)

[[1 2 3]
 [4 5 6]]
[[11.5]
 [12.5]
 [13.5]]
(2, 3) (3, 1) [[ 77. ]
 [189.5]]


### 25
Поменяйте знак всех чисел из интервала (3; 9), хранящихся в векторе Z.

Примечание. В этой задаче не нужно ничего выводить на печать. Только заменить некоторые элементы Z. 

In [90]:
Z = np.arange(11)

print((Z > 3) & (Z < 9))

Z[(Z > 3) & (Z < 9)] *= -1

Z

[False False False False  True  True  True  True  True False False]


array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])