На вход подаётся список чисел (строка, где числа разделены запятой).

Создайте и сохраните:

- в переменную V1 Numpy вектор из этих чисел в том же порядке
- в переменную V2 Numpy вектор, содержащий только предпоследнее число (это должен быть именно вектор!)
- в переменную V3 Numpy вектор из этих чисел в обратном порядке
- в переменную V4 Numpy вектор из этих чисел, начиная с 0-ого, через 2 (т.е. каждое третье число)
- в переменную V5 Numpy вектор, созданный из генератора Range, содержащий столько элементов, сколько было передано чисел на вход

Примечание. В этой задаче не нужно ничего выводить на печать. Только создать вектора.

In [8]:
import numpy as np

in_ = [1, 2, 3, 4, 5.0, 6, 7, 8, 9, 10]
in_ = input().split(', ')
in_ = list(map(float, in_))

V1 = np.array(in_)
V2 = np.array(in_[-2])
V3 = np.array(in_[::-1])
V4 = np.array(in_[::3])
V5 = np.array(range(len(in_)))

print(V5)

[0 1 2 3 4 5 6 7 8 9]


[](https://ucarecdn.com/0f65b331-4667-4c48-99e7-b192bc3f65e6/)

На вход подаётся 2 списка целых чисел (они представляют из себя вектора равной длины, т.е. с одинаковым количеством элементов).

Используя векторные операции создайте и сохраните:

- в переменную V1 Numpy вектор с числами из 1 строки
- в переменную V2 Numpy вектор с числами из 2 строки
- в переменную V3 Numpy вектор с покоординатными суммами V1 и V2
- в переменную V4 Numpy вектор с покоординатными произведениями каждого второго числа V1 на каждое второе число V2, развёрнутого в обратном порядке


In [19]:
l1 = '1, 2, 3, 4'
l2 = '10, 20, 30, 40'

V1 = np.array(list(map(int, l1.split(', '))))
V2 = np.array(list(map(int, l2.split(', '))))
V3 = V1 + V2
V4 = V1[::2] * V2[::-2]
V4

array([40, 60])

На вход подаётся 2 набора целых чисел.

Создайте вектор V такой, что он будет содержать числа из 1 набора, делящиеся нацело на предпоследнее число из 2 набора и разделённые на это число.

Если таких чисел не найдётся, то вектор V будет пустым (т.е. не будет содержать элементов).

 

Примечание. В этой задаче не нужно ничего выводить на печать. Только создать вектора.

In [26]:
l1 = '1, 2, 3, 4, 5, 6'
l2 = '1, 2, 3, 4'

V1 = np.array(list(map(int, l1.split(', '))))
V2 = np.array(list(map(int, l2.split(', '))))

V3_1 = np.array(V1 % V2[-2] == 0)
print(V3_1)

V3 =  V1[V1 % V2[-2] == 0] / V2[-2]
V3

[False False  True False False  True]


array([1., 2.])

В этой задаче нам даны 3 переменные: A1, A2, A3. Каждая содержит вектор с 2 координатами соответствующей вершины треугольника.

Найдите площадь треугольника и выведите её на печать.
Если все 3 точки лежат на одной прямой, то площадь треугольника равна 0.

Ответ проверяется с точностью до 4 знака после запятой.

In [41]:
from math import sqrt

A1 = np.array((-1, 1))
A2 = np.array((2, 5))
A3 = np.array((5, -3))

A1 = np.array((-1, 2))
A2 = np.array((2, 3))
A3 = np.array((5, 4))

l1 = sqrt((A1[0] - A2[0])**2 + (A1[1] - A2[1])**2)
l2 = sqrt((A1[0] - A3[0])**2 + (A1[1] - A3[1])**2)
l3 = sqrt((A2[0] - A3[0])**2 + (A2[1] - A3[1])**2)

#print(l1, l2, l3)
p = (l1 + l2 + l3)/2

S = sqrt(p*(p-l1)*(p-l2)*(p-l3))
print(S)

0.0


Переменная M1 содержит Numpy матрицу.

Произведите операции последовательно:

1. Замените значения в предпоследней строке на значения по формуле:

sin(x⋅π6)\LARGE sin(\frac{x \cdot \pi}{6})sin(6x⋅π), где x - старое значение

2. Замените значения в предпоследнем столбце на значения по форуме:

ex\LARGE e^xex

 

Примечание. Для ячейки на пересечении предпоследнего столбца и предпоследней строки значение ячейки будет изменено по формуле: 

esin(x⋅π6)\LARGE e^{sin(\frac{x \cdot \pi}{6})}esin(6x⋅π​)